on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_REPO }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
# Habilitar para el deploy en k8s
#    - uses: actions/checkout@master
#    - name: deploy to cluster
#      uses: steebchen/kubectl@v2.0.0
#      with: # defaults to latest kubectl binary version
#        config: ${{ secrets.KUBE_CONFIG_DATA }}
#        command: set image --record deployment/prueba3-cicd-app container=${{ secrets.DOCKER_REPO }}:${{ github.sha }}
#    - name: verify deployment
#      uses: steebchen/kubectl@v2.0.0
#      with:
#        config: ${{ secrets.KUBE_CONFIG_DATA }}
#        version: v1.21.0 # specify kubectl binary version explicitly
#        command: rollout status deployment/prueba3-cicd-app
